file = open("introduction.txt", "w")
file.write("My name is Vishal.\n")
file.write("I am an MCA student.\n")
file.write("I am learning Python for Data Analytics.\n")
file.close()

file = open("introduction.txt", "r")
content = file.read()
print("File Contents:")
print(content)
file.close()
